# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.event.user_registered:
        class: AppBundle\EventsBundle\EventListener\UserRegisteredListener
        arguments: ["@mailer"] 
        tags:
            - {name: kernel.event_listener, event:app.event.user_registered, method:handler} 