# GitHub Action for Symfony
name: Symfony Encore Bundle
on: [push, pull_request]
jobs:
  symfony:
    name: Symfony (PHP 7.2.5 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.2.5
          extensions: mbstring, xml, ctype, iconv, intl, gd
          coverage: xdebug #optional
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: |
          composer require symfony/webpack-encore-bundle
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      #- name: Run Tests
        #run: php bin/phpunit --coverage-text#!/bin/bash
